
import java.awt.Color;
import java.sql.Date;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jkmar
 */
public class MainFrame extends javax.swing.JDialog {

    /**
     * Creates new form MainFrame
     */
    public MainFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addFaculty = new javax.swing.JPanel();
        addFacultyLabel = new javax.swing.JLabel();
        addFacultyField = new javax.swing.JTextField();
        addFacultyButton = new javax.swing.JButton();
        addFacultyStatus = new javax.swing.JLabel();
        addRoom = new javax.swing.JPanel();
        addRoomLabel = new javax.swing.JLabel();
        DropRoomLabel = new javax.swing.JLabel();
        addRoomNameLabel = new javax.swing.JLabel();
        addRoomSeatsLabel = new javax.swing.JLabel();
        addRoomNameField = new javax.swing.JTextField();
        addRoomSeatsField = new javax.swing.JTextField();
        addRoomSubmitButton = new javax.swing.JButton();
        dropRoomNameCombobox = new javax.swing.JComboBox<>();
        dropRoomNameLabel = new javax.swing.JLabel();
        dropRoomSubmitButton = new javax.swing.JButton();
        addRoomStatusLabel = new javax.swing.JLabel();
        dropRoomStatusLabel = new javax.swing.JLabel();
        addDate = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        addDateLabel = new javax.swing.JLabel();
        dropDateLabel = new javax.swing.JLabel();
        addDateChooseLabel = new javax.swing.JLabel();
        addDateSubmitButton = new javax.swing.JButton();
        dropDateChooseCombobox = new javax.swing.JComboBox<>();
        dropDateChooseLabel = new javax.swing.JLabel();
        dropDateSubmitButton = new javax.swing.JButton();
        addDateStatusLabel = new javax.swing.JLabel();
        dropDateStatusLabel = new javax.swing.JLabel();
        addDateChooseSpinner = new javax.swing.JSpinner();
        addReservation = new javax.swing.JPanel();
        dropReservationNameCombobox = new javax.swing.JComboBox<>();
        dropReservationDateLabel = new javax.swing.JLabel();
        dropReservationDateCombobox = new javax.swing.JComboBox<>();
        reservationSeatLabel = new javax.swing.JLabel();
        reservationSeatField = new javax.swing.JTextField();
        addReservationSubmitButton = new javax.swing.JButton();
        addReservationStatusLabel = new javax.swing.JLabel();
        addReservationLabel = new javax.swing.JLabel();
        dropReservationLabel = new javax.swing.JLabel();
        dropReservationNameLabel = new javax.swing.JLabel();
        addReservationNameLabel = new javax.swing.JLabel();
        addReservationDateLabel = new javax.swing.JLabel();
        addReservationNameCombobox = new javax.swing.JComboBox<>();
        addReservationDateCombobox = new javax.swing.JComboBox<>();
        dropReservationSubmitButton = new javax.swing.JButton();
        dropReservationStatusLabel = new javax.swing.JLabel();
        statusFaculty = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        facultyStatusCombobox = new javax.swing.JComboBox<>();
        facultyStatusLabel = new javax.swing.JLabel();
        statusReservation = new javax.swing.JPanel();
        reservationStatusLabel = new javax.swing.JLabel();
        statusWaitlist = new javax.swing.JPanel();
        waitlistStatusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RoomScheduler");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Room Scheduler");

        addFacultyLabel.setText("Add Faculty Name:");

        addFacultyField.setColumns(20);

        addFacultyButton.setText("Submit");
        addFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyButtonActionPerformed(evt);
            }
        });

        addFacultyStatus.setText("       ");

        javax.swing.GroupLayout addFacultyLayout = new javax.swing.GroupLayout(addFaculty);
        addFaculty.setLayout(addFacultyLayout);
        addFacultyLayout.setHorizontalGroup(
            addFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFacultyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addFacultyStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addFacultyLayout.createSequentialGroup()
                        .addComponent(addFacultyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFacultyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFacultyButton)))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        addFacultyLayout.setVerticalGroup(
            addFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFacultyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFacultyLabel)
                    .addComponent(addFacultyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFacultyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFacultyStatus)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Faculty", addFaculty);

        addRoomLabel.setText("Add Room");

        DropRoomLabel.setText("Drop Room");

        addRoomNameLabel.setText("Room Name:");

        addRoomSeatsLabel.setText("Room Seats:");

        addRoomNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomNameFieldActionPerformed(evt);
            }
        });

        addRoomSubmitButton.setText("Add");
        addRoomSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomSubmitButtonActionPerformed(evt);
            }
        });

        dropRoomNameCombobox.setModel(new javax.swing.DefaultComboBoxModel(RoomQueries.getRoomList("name").toArray()));
        dropRoomNameCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRoomNameComboboxActionPerformed(evt);
            }
        });

        dropRoomNameLabel.setText("Room Name:");

        dropRoomSubmitButton.setText("Drop");
        dropRoomSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropRoomSubmitButtonActionPerformed(evt);
            }
        });

        addRoomStatusLabel.setText("  ");

        dropRoomStatusLabel.setText("  ");

        javax.swing.GroupLayout addRoomLayout = new javax.swing.GroupLayout(addRoom);
        addRoom.setLayout(addRoomLayout);
        addRoomLayout.setHorizontalGroup(
            addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRoomSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addRoomLayout.createSequentialGroup()
                        .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addRoomLabel)
                            .addGroup(addRoomLayout.createSequentialGroup()
                                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addRoomSeatsLabel)
                                    .addComponent(addRoomNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addRoomSeatsField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(addRoomNameField)))
                            .addComponent(addRoomStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(165, 165, 165)
                        .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DropRoomLabel)
                            .addGroup(addRoomLayout.createSequentialGroup()
                                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dropRoomSubmitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dropRoomNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dropRoomNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dropRoomStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        addRoomLayout.setVerticalGroup(
            addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomLabel)
                    .addComponent(DropRoomLabel))
                .addGap(40, 40, 40)
                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomNameLabel)
                    .addComponent(addRoomNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropRoomNameLabel)
                    .addComponent(dropRoomNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomSeatsLabel)
                    .addComponent(addRoomSeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomSubmitButton)
                    .addComponent(dropRoomSubmitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoomStatusLabel)
                    .addComponent(dropRoomStatusLabel))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add/Drop Room", addRoom);

        addDateLabel.setText("Add Date");

        dropDateLabel.setText("Drop Date");

        addDateChooseLabel.setText("Choose Date");

        addDateSubmitButton.setText("Add");
        addDateSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateSubmitButtonActionPerformed(evt);
            }
        });

        dropDateChooseCombobox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDateList().toArray()));

        dropDateChooseLabel.setText("Choose Date");

        dropDateSubmitButton.setText("Drop");
        dropDateSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDateSubmitButtonActionPerformed(evt);
            }
        });

        addDateStatusLabel.setText("  ");

        dropDateStatusLabel.setText("  ");

        addDateChooseSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1576189789242L), null, null, java.util.Calendar.DAY_OF_MONTH));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDateLabel)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(addDateChooseLabel)
                        .addGap(18, 18, 18)
                        .addComponent(addDateChooseSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addDateStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDateSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropDateSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDateLabel)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(dropDateChooseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dropDateChooseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dropDateStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDateLabel)
                    .addComponent(dropDateLabel))
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDateChooseLabel)
                    .addComponent(dropDateChooseLabel)
                    .addComponent(dropDateChooseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDateChooseSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDateSubmitButton)
                    .addComponent(dropDateSubmitButton))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDateStatusLabel)
                    .addComponent(dropDateStatusLabel))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addDateLayout = new javax.swing.GroupLayout(addDate);
        addDate.setLayout(addDateLayout);
        addDateLayout.setHorizontalGroup(
            addDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addDateLayout.setVerticalGroup(
            addDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDateLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add/Drop Date", addDate);

        dropReservationNameCombobox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        dropReservationNameCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropReservationNameComboboxActionPerformed(evt);
            }
        });

        dropReservationDateLabel.setText("Choose Date:");

        dropReservationDateCombobox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDateList().toArray()));
        dropReservationDateCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropReservationDateComboboxActionPerformed(evt);
            }
        });

        reservationSeatLabel.setText("Enter Number of Seats:");

        reservationSeatField.setColumns(4);
        reservationSeatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationSeatFieldActionPerformed(evt);
            }
        });

        addReservationSubmitButton.setText("Reserve");
        addReservationSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReservationSubmitButtonActionPerformed(evt);
            }
        });

        addReservationStatusLabel.setText(" ");

        addReservationLabel.setText("Add Reservation");

        dropReservationLabel.setText("Drop Reservation");

        dropReservationNameLabel.setText("Choose Faculty Name:");

        addReservationNameLabel.setText("Choose Faculty Name:");

        addReservationDateLabel.setText("Choose Date:");

        addReservationNameCombobox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));

        addReservationDateCombobox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDateList().toArray()));

        dropReservationSubmitButton.setText("Drop");
        dropReservationSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropReservationSubmitButtonActionPerformed(evt);
            }
        });

        dropReservationStatusLabel.setText(" ");

        javax.swing.GroupLayout addReservationLayout = new javax.swing.GroupLayout(addReservation);
        addReservation.setLayout(addReservationLayout);
        addReservationLayout.setHorizontalGroup(
            addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addReservationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addReservationStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addReservationLayout.createSequentialGroup()
                        .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addReservationSubmitButton)
                                .addGroup(addReservationLayout.createSequentialGroup()
                                    .addComponent(reservationSeatLabel)
                                    .addGap(8, 8, 8)))
                            .addComponent(addReservationLabel)
                            .addComponent(addReservationDateLabel)
                            .addComponent(addReservationNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addReservationLayout.createSequentialGroup()
                                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addReservationDateCombobox, 0, 100, Short.MAX_VALUE)
                                    .addComponent(addReservationNameCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(179, 179, 179)
                                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dropReservationLabel)
                                    .addGroup(addReservationLayout.createSequentialGroup()
                                        .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addReservationLayout.createSequentialGroup()
                                                .addComponent(dropReservationDateLabel)
                                                .addGap(69, 69, 69))
                                            .addGroup(addReservationLayout.createSequentialGroup()
                                                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(dropReservationSubmitButton)
                                                    .addComponent(dropReservationNameLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dropReservationNameCombobox, 0, 100, Short.MAX_VALUE)
                                            .addComponent(dropReservationDateCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(dropReservationStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(reservationSeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        addReservationLayout.setVerticalGroup(
            addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addReservationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addReservationLabel)
                    .addComponent(dropReservationLabel))
                .addGap(32, 32, 32)
                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropReservationNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropReservationNameLabel)
                    .addComponent(addReservationNameLabel)
                    .addComponent(addReservationNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropReservationDateLabel)
                    .addComponent(dropReservationDateCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addReservationDateLabel)
                    .addComponent(addReservationDateCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservationSeatLabel)
                    .addComponent(reservationSeatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addReservationSubmitButton)
                    .addComponent(dropReservationSubmitButton))
                .addGap(18, 18, 18)
                .addGroup(addReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addReservationStatusLabel)
                    .addComponent(dropReservationStatusLabel))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add/Drop Reservation", addReservation);

        jLabel2.setText("Faculty Member Name:");

        facultyStatusCombobox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        facultyStatusCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyStatusComboboxActionPerformed(evt);
            }
        });

        facultyStatusLabel.setText(" ");

        javax.swing.GroupLayout statusFacultyLayout = new javax.swing.GroupLayout(statusFaculty);
        statusFaculty.setLayout(statusFacultyLayout);
        statusFacultyLayout.setHorizontalGroup(
            statusFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusFacultyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultyStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(statusFacultyLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(facultyStatusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 654, Short.MAX_VALUE)))
                .addContainerGap())
        );
        statusFacultyLayout.setVerticalGroup(
            statusFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusFacultyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(facultyStatusCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(facultyStatusLabel)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Faculty Status", statusFaculty);

        reservationStatusLabel.setText(ReservationQueries.setStatusText());

        javax.swing.GroupLayout statusReservationLayout = new javax.swing.GroupLayout(statusReservation);
        statusReservation.setLayout(statusReservationLayout);
        statusReservationLayout.setHorizontalGroup(
            statusReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusReservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservationStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        statusReservationLayout.setVerticalGroup(
            statusReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusReservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservationStatusLabel)
                .addContainerGap(483, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reservation Status", statusReservation);

        waitlistStatusLabel.setText(WaitlistQueries.setStatusText());

        javax.swing.GroupLayout statusWaitlistLayout = new javax.swing.GroupLayout(statusWaitlist);
        statusWaitlist.setLayout(statusWaitlistLayout);
        statusWaitlistLayout.setHorizontalGroup(
            statusWaitlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusWaitlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitlistStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        statusWaitlistLayout.setVerticalGroup(
            statusWaitlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusWaitlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitlistStatusLabel)
                .addContainerGap(483, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Waitlist Status", statusWaitlist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropRoomSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRoomSubmitButtonActionPerformed
        // TODO add your handling code here:
        try {
            String roomName = dropRoomNameCombobox.getSelectedItem().toString();
            String status = "<html>" + roomName + " has been removed from the system.<br>";
            status += RoomQueries.dropRoom(roomName);

            dropRoomStatusLabel.setForeground(Color.BLACK);
            dropRoomStatusLabel.setText(status);

            rebuildRoomComboBox();
        } catch(Exception e) {
            //catches error from addRoom sets different status message
            dropRoomStatusLabel.setForeground(Color.RED);
            dropRoomStatusLabel.setText("No room has been removed from the system.");
        }
        setStatusLabels();
    }//GEN-LAST:event_dropRoomSubmitButtonActionPerformed

    private void addRoomSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomSubmitButtonActionPerformed
        // TODO add your handling code here:
        String roomName = addRoomNameField.getText();
        int roomSeats = Integer.parseInt(addRoomSeatsField.getText());

        try {
            String status = "<html>" + roomName + " has been added to the system.<br>";
            status += RoomQueries.addRoom(new RoomEntry(roomName, roomSeats));
            
            status += "</html>";
            //Set the status text
            addRoomStatusLabel.setForeground(Color.BLACK);
            addRoomStatusLabel.setText(status);

            //Reset Combo Box, update statuses
            rebuildRoomComboBox();
            setStatusLabels();
        } catch(Exception e) {
            //catches error from addRoom sets different status message
            addRoomStatusLabel.setForeground(Color.RED);
            addRoomStatusLabel.setText(roomName + " has not been added to the system.");
        }
        setStatusLabels();
    }//GEN-LAST:event_addRoomSubmitButtonActionPerformed

    private void addRoomNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRoomNameFieldActionPerformed

    private void addFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyButtonActionPerformed
        //Adds Faculty Member
        //Get Info from addFacultyField
        String facultyName = addFacultyField.getText();

        //Add faculty member to database if they are not found
        try {
            //Adds faculty name to db throws error if duplicate key
            Faculty.addFaculty(facultyName);

            //Set the status text
            addFacultyStatus.setForeground(Color.BLACK);
            addFacultyStatus.setText(facultyName + " has been added to the system.");

            //Reset Combo Boxes
            rebuildFacultyComboBox();
        } catch(Exception e) {
            //catches error from addFaculty sets different status message
            addFacultyStatus.setForeground(Color.RED);
            addFacultyStatus.setText(facultyName + " has not been added to the system.");
        }
    }//GEN-LAST:event_addFacultyButtonActionPerformed

    private void dropDateSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDateSubmitButtonActionPerformed
        // TODO add your handling code here:      
        try {
            Date day = Date.valueOf(dropDateChooseCombobox.getSelectedItem().toString());
            String status = Dates.dropDate(day);
            
            dropDateStatusLabel.setForeground(Color.BLACK);
            dropDateStatusLabel.setText(status);

            rebuildDateComboBox();
            
            setStatusLabels();
        } catch(Exception e) {
            //catches error from addRoom sets different status message
            dropDateStatusLabel.setForeground(Color.RED);
            dropDateStatusLabel.setText("No date has been removed from the system.");
        }
    }//GEN-LAST:event_dropDateSubmitButtonActionPerformed

    private void addDateSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateSubmitButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(addDateChooseSpinner.getValue());
        Date day = Date.valueOf(spinnerValue);
        
        try {
            Dates.addDate(day);
            
            //Set the status text
            addDateStatusLabel.setForeground(Color.BLACK);
            addDateStatusLabel.setText("Date " + day + " has been added to the system.");
            
            //Reset Combo Boxes
            rebuildDateComboBox();
        } catch(Exception e) {
            //catches error from addFaculty sets different status message
            addDateStatusLabel.setForeground(Color.RED);
            addDateStatusLabel.setText("Date " + day + " has not been added to the system.");
        }
    }//GEN-LAST:event_addDateSubmitButtonActionPerformed

    private void facultyStatusComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyStatusComboboxActionPerformed
        // TODO add your handling code here:
        String facultyMember = facultyStatusCombobox.getSelectedItem().toString();
        facultyStatusLabel.setText(Faculty.setStatusText(facultyMember));
    }//GEN-LAST:event_facultyStatusComboboxActionPerformed

    private void addReservationSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReservationSubmitButtonActionPerformed
        //Reserves room for faculty member on given date
        //Retrieve given information
        String facultyName = addReservationNameCombobox.getSelectedItem().toString();
        Date day = Date.valueOf(addReservationDateCombobox.getSelectedItem().toString());
        int seats = Integer.parseInt(reservationSeatField.getText());
        RoomEntry room = RoomQueries.reserveRoom(seats, day);
        Timestamp timestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        
        

        if(room == null) {
            WaitlistEntry entry = new WaitlistEntry(facultyName, day, seats, timestamp);
            try {
                WaitlistQueries.addWaitlistEntry(entry);
            } catch (SQLIntegrityConstraintViolationException ex) {
                //If a duplicate key is entered
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            addReservationStatusLabel.setText("No room found: " + facultyName + " has been waitlisted for " + day);
        } else {
            ReservationEntry entry = new ReservationEntry(facultyName, room.getName(), day, seats, timestamp);
            try {
                ReservationQueries.addReservationEntry(entry);
            } catch (SQLIntegrityConstraintViolationException ex) {
                //If a duplicate key is entered
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            addReservationStatusLabel.setText(facultyName + " has successfully reserved room " + room.getName() + " for " + day);
        }
        setStatusLabels();
    }//GEN-LAST:event_addReservationSubmitButtonActionPerformed

    private void reservationSeatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationSeatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationSeatFieldActionPerformed

    private void dropReservationNameComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropReservationNameComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropReservationNameComboboxActionPerformed

    private void dropReservationDateComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropReservationDateComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropReservationDateComboboxActionPerformed

    private void dropReservationSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropReservationSubmitButtonActionPerformed
        // TODO add your handling code here:
        try {
            String name = dropReservationNameCombobox.getSelectedItem().toString();
            Date day = Date.valueOf(dropReservationDateCombobox.getSelectedItem().toString());
            
            dropReservationStatusLabel.setForeground(Color.BLACK);
            String statusText = "<html>Reservation for " + name + " on " + day + " has been removed from the system.";
            ReservationEntry entry = ReservationQueries.cancelReservationEntry(name, day);
            if(entry != null) {
                statusText += "<br>" + entry.getRoom() + " has been reserved for " + entry.getName() + " on " + entry.getDate();
            }
            dropReservationStatusLabel.setText(statusText);
        } catch(Exception e) {
            //catches error from addRoom sets different status message
            dropReservationStatusLabel.setForeground(Color.RED);
            dropReservationStatusLabel.setText("No reservation has been removed from the system.");
        }
        setStatusLabels();
    }//GEN-LAST:event_dropReservationSubmitButtonActionPerformed

    private void dropRoomNameComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropRoomNameComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropRoomNameComboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame dialog = new MainFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DropRoomLabel;
    private javax.swing.JPanel addDate;
    private javax.swing.JLabel addDateChooseLabel;
    private javax.swing.JSpinner addDateChooseSpinner;
    private javax.swing.JLabel addDateLabel;
    private javax.swing.JLabel addDateStatusLabel;
    private javax.swing.JButton addDateSubmitButton;
    private javax.swing.JPanel addFaculty;
    private javax.swing.JButton addFacultyButton;
    private javax.swing.JTextField addFacultyField;
    private javax.swing.JLabel addFacultyLabel;
    private javax.swing.JLabel addFacultyStatus;
    private javax.swing.JPanel addReservation;
    private javax.swing.JComboBox<String> addReservationDateCombobox;
    private javax.swing.JLabel addReservationDateLabel;
    private javax.swing.JLabel addReservationLabel;
    private javax.swing.JComboBox<String> addReservationNameCombobox;
    private javax.swing.JLabel addReservationNameLabel;
    private javax.swing.JLabel addReservationStatusLabel;
    private javax.swing.JButton addReservationSubmitButton;
    private javax.swing.JPanel addRoom;
    private javax.swing.JLabel addRoomLabel;
    private javax.swing.JTextField addRoomNameField;
    private javax.swing.JLabel addRoomNameLabel;
    private javax.swing.JTextField addRoomSeatsField;
    private javax.swing.JLabel addRoomSeatsLabel;
    private javax.swing.JLabel addRoomStatusLabel;
    private javax.swing.JButton addRoomSubmitButton;
    private javax.swing.JComboBox<String> dropDateChooseCombobox;
    private javax.swing.JLabel dropDateChooseLabel;
    private javax.swing.JLabel dropDateLabel;
    private javax.swing.JLabel dropDateStatusLabel;
    private javax.swing.JButton dropDateSubmitButton;
    private javax.swing.JComboBox<String> dropReservationDateCombobox;
    private javax.swing.JLabel dropReservationDateLabel;
    private javax.swing.JLabel dropReservationLabel;
    private javax.swing.JComboBox<String> dropReservationNameCombobox;
    private javax.swing.JLabel dropReservationNameLabel;
    private javax.swing.JLabel dropReservationStatusLabel;
    private javax.swing.JButton dropReservationSubmitButton;
    private javax.swing.JComboBox<String> dropRoomNameCombobox;
    private javax.swing.JLabel dropRoomNameLabel;
    private javax.swing.JLabel dropRoomStatusLabel;
    private javax.swing.JButton dropRoomSubmitButton;
    private javax.swing.JComboBox<String> facultyStatusCombobox;
    private javax.swing.JLabel facultyStatusLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField reservationSeatField;
    private javax.swing.JLabel reservationSeatLabel;
    private javax.swing.JLabel reservationStatusLabel;
    private javax.swing.JPanel statusFaculty;
    private javax.swing.JPanel statusReservation;
    private javax.swing.JPanel statusWaitlist;
    private javax.swing.JLabel waitlistStatusLabel;
    // End of variables declaration//GEN-END:variables

    private void rebuildFacultyComboBox() {
        addReservationNameCombobox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        dropReservationNameCombobox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        facultyStatusCombobox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
    }

    private void rebuildRoomComboBox() {
        dropRoomNameCombobox.setModel(new javax.swing.DefaultComboBoxModel(RoomQueries.getRoomList("name").toArray()));
    }
    
    private void rebuildDateComboBox() {
        addReservationDateCombobox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDateList().toArray()));
        dropReservationDateCombobox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDateList().toArray()));
        dropDateChooseCombobox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDateList().toArray()));
    }
    
    private void setStatusLabels() {
        reservationStatusLabel.setText(ReservationQueries.setStatusText());
        waitlistStatusLabel.setText(WaitlistQueries.setStatusText());
    }
}
